package com.rajput.cookingrecipe.model

import com.rajput.cookingrecipe.R
import com.rajput.cookingrecipe.data.RecipeData

object RecipeBook {
    val recipes = listOf(
        RecipeData(
            R.string.day_1,
            R.drawable.recipe_1,
            R.string.recipe_1,
            R.string.recipe_1_description
        ),
        RecipeData(
            R.string.day_2,
            R.drawable.recipe_2,
            R.string.recipe_2,
            R.string.recipe_2_description
        ),
        RecipeData(
            R.string.day_3,
            R.drawable.recipe_3,
            R.string.recipe_3,
            R.string.recipe_3_description
        ),
        RecipeData(
            R.string.day_4,
            R.drawable.recipe_4,
            R.string.recipe_4,
            R.string.recipe_4_description
        ),
        RecipeData(
            R.string.day_5,
            R.drawable.recipe_5,
            R.string.recipe_5,
            R.string.recipe_5_description
        ),
        RecipeData(
            R.string.day_6,
            R.drawable.recipe_6,
            R.string.recipe_6,
            R.string.recipe_6_description
        ),
        RecipeData(
            R.string.day_7,
            R.drawable.recipe_7,
            R.string.recipe_7,
            R.string.recipe_7_description
        ),
        RecipeData(
            R.string.day_8,
            R.drawable.recipe_8,
            R.string.recipe_8,
            R.string.recipe_8_description
        ),
        RecipeData(
            R.string.day_9,
            R.drawable.recipe_9,
            R.string.recipe_9,
            R.string.recipe_9_description
        ),
        RecipeData(
            R.string.day_10,
            R.drawable.recipe_10,
            R.string.recipe_10,
            R.string.recipe_10_description
        ),
        RecipeData(
            R.string.day_11,
            R.drawable.recipe_11,
            R.string.recipe_11,
            R.string.recipe_11_description
        ),
        RecipeData(
            R.string.day_12,
            R.drawable.recipe_12,
            R.string.recipe_12,
            R.string.recipe_12_description
        ),
        RecipeData(
            R.string.day_13,
            R.drawable.recipe_13,
            R.string.recipe_13,
            R.string.recipe_13_description
        ),
        RecipeData(
            R.string.day_14,
            R.drawable.recipe_14,
            R.string.recipe_14,
            R.string.recipe_14_description
        ),
        RecipeData(
            R.string.day_15,
            R.drawable.recipe_15,
            R.string.recipe_15,
            R.string.recipe_15_description
        ),
        RecipeData(
            R.string.day_16,
            R.drawable.recipe_16,
            R.string.recipe_16,
            R.string.recipe_16_description
        ),
        RecipeData(
            R.string.day_17,
            R.drawable.recipe_17,
            R.string.recipe_17,
            R.string.recipe_17_description
        ),
        RecipeData(
            R.string.day_18,
            R.drawable.recipe_18,
            R.string.recipe_18,
            R.string.recipe_18_description
        ),
        RecipeData(
            R.string.day_19,
            R.drawable.recipe_19,
            R.string.recipe_19,
            R.string.recipe_19_description
        ),
        RecipeData(
            R.string.day_20,
            R.drawable.recipe_20,
            R.string.recipe_20,
            R.string.recipe_20_description
        ),
        RecipeData(
            R.string.day_21,
            R.drawable.recipe_21,
            R.string.recipe_21,
            R.string.recipe_21_description
        ),
        RecipeData(
            R.string.day_22,
            R.drawable.recipe_22,
            R.string.recipe_22,
            R.string.recipe_22_description
        ),
        RecipeData(
            R.string.day_23,
            R.drawable.recipe_23,
            R.string.recipe_23,
            R.string.recipe_23_description
        ),
        RecipeData(
            R.string.day_24,
            R.drawable.recipe_24,
            R.string.recipe_24,
            R.string.recipe_24_description
        ),
        RecipeData(
            R.string.day_25,
            R.drawable.recipe_25,
            R.string.recipe_25,
            R.string.recipe_25_description
        ),
        RecipeData(
            R.string.day_26,
            R.drawable.recipe_26,
            R.string.recipe_26,
            R.string.recipe_26_description
        ),
        RecipeData(
            R.string.day_27,
            R.drawable.recipe_27,
            R.string.recipe_27,
            R.string.recipe_27_description
        ),



    )
}